---
- name: Checkout snarkOS from git and build
  become_user: "{{ snarkos_user }}"
  block:
    - name: Clone snarkOS repository
      git:
        repo: 'https://github.com/AleoHQ/snarkOS.git'
        dest: "{{ working_directory }}/snarkOS"
        version: main
        update: yes
    - name: Build snarkOS
      command:
        cmd: cargo build --release
        chdir: "{{ working_directory }}/snarkOS"
      environment:
        PATH: "{{ working_directory }}/.cargo/bin:{{ ansible_env.PATH }}"
    - name: Create bin directory and move snarkOS binary
      file:
        path: "{{ working_directory }}/bin"
        state: directory
    - command: mv "{{ working_directory }}/snarkOS/target/release/snarkos" "{{ working_directory }}/bin/snarkos"
      args:
        removes: "{{ working_directory }}/bin/snarkos"