---
- name: Upgrade snarkOS
  become_user: "{{ snarkos_user }}"
  block:
    - name: Stop snarkOS service
      systemd:
        name: snarkos
        state: stopped

    - name: Update snarkOS repository
      git:
        repo: 'https://github.com/AleoHQ/snarkOS.git'
        dest: "{{ working_directory }}/snarkOS"
        version: main
        update: yes

    - name: Rebuild snarkOS
      command:
        cmd: cargo build --release
        chdir: "{{ working_directory }}/snarkOS"
      environment:
        PATH: "{{ working_directory }}/.cargo/bin:{{ ansible_env.PATH }}"

    - name: Move new snarkOS binary
      command: mv "{{ working_directory }}/snarkOS/target/release/snarkos" "{{ working_directory }}/bin/snarkos"
      args:
        removes: "{{ working_directory }}/bin/snarkos"

    - name: Start snarkOS service
      systemd:
        name: snarkos
        state: started