---
- name: Install snarkOS
  hosts: snarkos_hosts
  become: yes
  vars_files:
    - ../vars/snarkos_vars.yml
  roles:
    - snarkos
  tasks:
    - include_role:
        name: snarkos
        tasks_from: install_snarkos