---
- name: Stop snarkOS service
  hosts: snarkos_hosts
  become: yes
  vars_files:
    - ../vars/snarkos_vars.yml
  roles:
    - snarkos
  tasks:
    - include_role:
        name: snarkos
        tasks_from: manage_service
      vars:
        service_action: stop